remove domInput and stayOnTop support in wechat
cocos-creator/weapp-adapter pull request #42
Opened 2018-09-06 05:18 UTC by umbrellaPP

Re:
https://github.com/cocos-creator/fireball/issues/8348
https://github.com/cocos-creator/fireball/issues/8357

小游戏 editBox 整理：
- 移除 domInput， 小游戏上对 domInput 适配不是很好，不能设置 value placeHolder
  所以这里改为在 touchEnded 的时候去 createInput。小游戏里其实不需要创建 domInput
- 重新适配了 setFocus  和 isFocused api
- 修复 多个 editBox 监听 input 事件的问题
- 修复 设置 stayOnTop 会把 label 隐藏的问题

2018-09-06 07:26 UTC, umbrellaPP commented on wechatgame/libs/engine/Editbox.js
> +        }
这里是修复多个 editBox 同时监听 input 事件的问题

2018-09-06 07:26 UTC, umbrellaPP commented on wechatgame/libs/engine/Editbox.js
> +    };
避免 设置 stayOnTop label 被隐藏

2018-09-06 09:25 UTC, pandamicro requested changes

2018-09-06 09:29 UTC, umbrellaPP commented on wechatgame/libs/engine/Editbox.js
> -    _p._beginEditing = function () {
_beginEditing 默认是在 touchEnded 里边调用的，这里边实现的是 domInput 的现实控制，和调用domInput.focus() ，这些在小游戏里边都是不需要的，现在重写了  touchEnded，就没有调用 _beginEditing 方法了

2018-09-06 09:48 UTC, umbrellaPP commented on wechatgame/libs/engine/Editbox.js
> +    };
嗯嗯，漏了，是有问题的，我待会补充下

2018-09-06 10:54 UTC, pandamicro commented on wechatgame/libs/engine/Editbox.js
> +    _p._onTouchEnded = function () {
_p._beginEditing = _p.createInput;

2018-09-07 02:01 UTC, pandamicro approved these changes

2018-09-07 02:01 UTC, merged