[WIP] move in CC_WECHATGAME logic
cocos-creator/weapp-adapter pull request #85
Opened 2019-04-24 02:54 UTC by umbrellaPP

https://github.com/cocos-creator/2d-tasks/issues/1360

将引擎 `CC_WECHATGAME` 和 `BROWSER_TYPE_WECHATGAME` `BROWSER_TYPE_WECHATGAME_SUB` 相关的代码移进 adapter

2019-05-05 11:18 UTC, pandamicro requested changes

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/libs/engine/Game.js
> +        this.container = localContainer = document.createElement("DIV");
其实微信等小游戏平台不需要 container 了，可以检查一下引擎中对 container 的使用，没问题就去掉把

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/libs/engine/Game.js
> +        }
拆分出来的意义就在于不需要上面这些其他环境下的适配代码了，

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/libs/engine/Game.js
> +        }
同上

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/libs/engine/InputManager.js
> +        };
不要每次调用都创建对象，用同一个缓存

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/libs/engine/InputManager.js
> +        return {x: event.clientX, y: event.clientY};
同样的道理，看看这个接口能否优化，由调用者提供 out point 对象

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/libs/engine/preAdaptEngine/ContainerStrategy.js
> +    _setupContainer (view, w, h) {
这个函数貌似是可以做到统一的

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/libs/engine/preAdaptEngine/View.js
> +    setRealPixelResolution (width, height, resolutionPolicy) {
这里要先手动设置 canvas 尺寸

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/main.js
> +                    }
这个不需要了

2019-05-05 11:18 UTC, pandamicro commented on wechatgame/libs/engine/preAdaptEngine/macro.js
> +    WECHAT_GAME: 104,
貌似不太合适，新添加一个平台的时候，要怎么知道应该用什么数字？怎么查到已经被使用的数字？

2019-05-07 01:50 UTC, pandamicro requested changes

2019-05-07 01:50 UTC, pandamicro commented on wechatgame/libs/engine/Game.js
> +        };
这个函数删除，在这些小游戏平台没有意义

2019-05-29 05:29 UTC, pandamicro commented on wechatgame/libs/engine/Game.js
> +        }
从 inputManager.registerSystemEvent 这句代码之后，到这里以上全部不需要

2019-05-29 05:29 UTC, pandamicro commented on wechatgame/libs/wx-downloader.js
> +const isSubContext = !wx.getOpenDataContext;
这个貌似不太靠谱了，看看有没有更好的方法判定

2019-05-29 06:27 UTC, umbrellaPP commented on wechatgame/libs/wx-downloader.js
> +const isSubContext = !wx.getOpenDataContext;
这里貌似现在只有这个方法比较靠谱了，开放域是绝对没有 getOpenDataContext 接口的。我把它改成这样吧
```
const isSubContext =(cc.sys.platform === cc.sys.WECHAT_GAME_SUB);
```

虽然 platform 的初始化也是根据 wx.getOpenDataContext 来判断的，这样改的好处是以后可以在初始化 platform 信息的时候统一修改子域的判断

2019-05-29 08:02 UTC, umbrellaPP commented on wechatgame/libs/engine/Game.js
> +            game.emit(game.EVENT_SHOW, res);
https://developers.weixin.qq.com/minigame/dev/api/base/app/life-cycle/wx.onShow.html

2019-06-03 08:29 UTC, pandamicro requested changes

2019-06-03 08:29 UTC, pandamicro commented on wechatgame/libs/engine/globalAdapter/View.js
> +            // wx not support
加上 warning 比较好

2019-06-03 08:29 UTC, pandamicro commented on wechatgame/libs/engine/globalAdapter/View.js
> +            // wx not support
同上，所有公开 API 如果某些平台不支持，都需要给出明确的提示

2019-06-03 08:30 UTC, pandamicro commented on wechatgame/libs/wx-downloader.js
> +const isSubContext = !wx.getOpenDataContext;
嗯，可以

2019-06-14 03:05 UTC, pandamicro approved these changes

2019-06-14 03:05 UTC, merged